---

- name: libvirt dependencies are installed
  package:
    name: "{{ hashicorp_packages_libvirt }}"
    state: present
  become: true

- name: vagrant libvirt is installed                  # noqa 305
  shell: /opt/vagrant/bin/vagrant plugin install vagrant-libvirt
  environment:
    CONFIGURE_ARGS: "with-ldflags=-L/opt/vagrant/embedded/lib \
      with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib"
    GEM_HOME: "~/.vagrant.d/gems"
    GEM_PATH: "$GEM_HOME:/opt/vagrant/embedded/gems"
    PATH: "/opt/vagrant/embedded/bin:$PATH"
  args:
    executable: /bin/sh
    creates: "~/.vagrant.d/plugins.json"
  tags:
    - hashicorp_vagrant_libvirt
  become: false
